[project]
name = "prompt-optimization-textgrad-dysp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dspy>=2.6.27",
    "ipykernel>=6.29.5",
    "textgrad>=0.1.8",
]
